### ISSUE TITLE
English date and time on the interview confirmation page

### ISSUE THREAD

**Issue by joriki** [DemokratieInBewegung/appntr#2]
The interview confirmation page (appntr/templates/interviews/confirm.html) uses English date and time formats: "Friday, 20. October 2017 um 11 a.m." (it should say something like "Freitag, den 20. Oktober 2017 um 11:00 Uhr"). According to [this Django reference](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-TIME_FORMAT), the setting [USE_L10N](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-USE_L10N) would have to be `True` for the format to be localized.

**Comment by crunchy-amarillo** [comment]
@joriki  While my tests there has always been a german formated date. (screenshot) 
Maybe it's localized or fixed anyway? 

![localhost_8000_einladung_5e74af572e 1](https://user-images.githubusercontent.com/33552667/32677517-03933336-c65f-11e7-97f9-47344ef78d00.png)

**Comment by joriki** [comment]
I'm closing this as the date and time now appear in German for me too.
