### ISSUE TITLE
Formular erweitern um bisherige Beteiligung

### ISSUE THREAD

**Issue by gnunicorn** [DemokratieInBewegung/appntr#4]
- eine Checkbox: "Ich habe bereits an Aktionen von DiB teilgenommen" --> ja/nein
- ein Textfeld, optional, "Wenn ja, welche Aktionen hat Du bereits mitgemacht - bitte kurz aufzählen: (z.B. Initiative eingereicht, Unterschriften gesammelt, Stände betreut, DiB-Tische besucht etc.):"
 - ein Textfeld, optional, "Ich bin bereits mit folgenden DiB-Aktiven im Kontakt: //Eingabefeld//"

Soll in der Einzellansicht unterhalb der anderen Informationen für alle einsehbar sein.

**Comment by crunchy-amarillo** [comment]
Ist live installiert
